HealthyLifeStyle.Web/Models/Home/ListViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace HealthyLifeStyle.Web.Models.Home
{
    public class ListViewModel
    {
       
        public string Name { get; set; }
        
        public string Phone { get; set; }

        public string Address { get; set; }
    }
}

HealthyLifeStyle.Web/Models/Hospital/AddViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace HealthyLifeStyle.Web.Models.Hospital
{
    public class AddViewModel
    {
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        
    }
}

HealthyLifeStyle.Web/Models/Hospital/ListViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace HealthyLifeStyle.Web.Models.Hospital
{
    public class ListViewModel
    {

        public int Id { get; set; }
       
        public string Name { get; set; }
        
        public string Phone { get; set; }
       
        public string Address { get; set; }
    }
}

HealthyLifeStyle.Web/Models/NeedForBlood/AddViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;

namespace HealthyLifeStyle.Web.Models.NeedForBlood
{
    public class AddViewModel
    {
        public int Id { get; set; }

        [Required]
        public int BloodGroupId { get; set; }

        [Required]
        public int Count { get; set; }

        //select list
        public List<SelectListItem>? BloodGroupSelectList { get; set; }
    }
}

HealthyLifeStyle.Web/Models/NeedForBlood/ListViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace HealthyLifeStyle.Web.Models.NeedForBlood
{
    public class ListViewModel
    {
        public int Id { get; set; }
      
        public string BloodGroup_Name { get; set; }
       
        public int HospitalId { get; set; }
       
        public int Count { get; set; }
    }
}

HealthyLifeStyle.Web/Models/User/AddViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;

namespace HealthyLifeStyle.Web.Models.User
{
    public class AddViewModel
    {
   
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        public string LastName { get; set; }

        [Required]
        public int BloodGroupId { get; set; }
   
        public string GSM { get; set; }

        [Required]
        public string UserName { get; set; }

        [Required]
        public string Password { get; set; }

        public int? HospitalId { get; set; }

        //select list
        public List<SelectListItem>? BloodGroupSelectList { get; set; }
        public List<SelectListItem>? HospitalSelectList { get; set; }
    }
}

HealthyLifeStyle.Web/Models/User/ListViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace HealthyLifeStyle.Web.Models.User
{
    public class ListViewModel
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public string LastName { get; set; }
        
        public string GSM { get; set; }

        public string UserName { get; set; }

        public int UserType { get; set; }


        public string BloodGroup_Name { get; set; }
        public string Hospital_Name { get; set; }
    }
}

HealthyLifeStyle.Web/Controllers/HospitalController.cs
using HealthyLifeStyle.Business.Interfaces;
using HealthyLifeStyle.Web.Models.Common;
using HealthyLifeStyle.Web.Models.Hospital;
using Microsoft.AspNetCore.Mvc;

namespace HealthyLifeStyle.Web.Controllers
{
    public class HospitalController : Controller
    {

        private readonly IHospitalService _hospitalService;

        public HospitalController(IHospitalService hospitalService)
        {
            _hospitalService = hospitalService;
        }
        public IActionResult List()
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("HealthyLifeStyle_User_Id")))
            {
                return RedirectToAction("Login", "User");
            }
            if (HttpContext.Session.GetInt32("HealthyLifeStyle_User_UserType") != (int)UserType.Admin)
            {
                return RedirectToAction("NotAuthorized", "User");
            }

            List<ListViewModel> model =  new List<ListViewModel>();
           
            try
            {
                var hospitalList = _hospitalService.GetAll();
                if (hospitalList !=null && hospitalList.Count>0)
                {
                    foreach (var item in hospitalList)
                    {
                        ListViewModel hospital = new ListViewModel()
                        {
                            Address = item.Address,
                            Id = item.Id,
                            Name = item.Name,
                            Phone = item.Phone
                        };
                        model.Add(hospital);
                    }
                }
            }
            catch
            {
                ViewBag.ErrorMessage = "Error";
            }
            return View(model);
        }

        public IActionResult Add()
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("HealthyLifeStyle_User_Id")))
            {
                return RedirectToAction("Login", "User");
            }
            if (HttpContext.Session.GetInt32("HealthyLifeStyle_User_UserType") != (int)UserType.Admin)
            {
                return RedirectToAction("NotAuthorized", "User");
            }
            AddViewModel model = new AddViewModel();
            return View(model);
        }

        [HttpPost]
        public IActionResult Add(AddViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            HealthyLifeStyle.Types.Entity.Hospital hospital = new Types.Entity.Hospital ();
            hospital.Name = model.Name; 
            hospital.Phone = model.Phone;
            hospital.Address = model.Address;

            try
            {
                _hospitalService.Add(hospital);
                return RedirectToAction(nameof(HospitalController.List));
            }
            catch
            {
                ViewBag.ErrorMessage = "Not Saved.";
                return View(model);
            }
        }

        public IActionResult Edit(int id)
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("HealthyLifeStyle_User_Id")))
            {
                return RedirectToAction("Login", "User");
            }
            if (HttpContext.Session.GetInt32("HealthyLifeStyle_User_UserType") != (int)UserType.Admin)
            {
                return RedirectToAction("NotAuthorized", "User");
            }
            AddViewModel model = new AddViewModel();
            try
            {
                var result = _hospitalService.GetById(id);
                if (result == null)
                {
                    return View("_ErrorNotExist");
                }
                model.Id = result.Id;
                model.Name = result.Name;
                model.Phone = result.Phone;
                model.Address = result.Address;
                return View(model);
            }
            catch (Exception)
            {
                ViewBag.ErrorMessage = "Record Not Found";
                return View("_ErrorNotExist");
            }
        }

        [HttpPost]
        public IActionResult Edit(AddViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                var hospital = _hospitalService.GetById(model.Id);
                if (hospital == null)
                {
                    return View("_ErrorNotExist");
                }

                hospital.Name = model.Name; 
                hospital.Phone = model.Phone;
                hospital.Address = model.Address;
               
                _hospitalService.Update(hospital);
                return RedirectToAction(nameof(HospitalController.List));
            }
            catch
            {
                ViewBag.ErrorMessage = "Not Saved.";
                return View(model);
            }
        }
    }
}

HealthyLifeStyle.Web/Views/Hospital/Add.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Hastane Ekleme";
}

@model HealthyLifeStyle.Web.Models.Hospital.AddViewModel

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <strong>Hospital Add</strong>
            </div>
            <div class="card-body">

                @using (Html.BeginForm("Add", "Hospital", FormMethod.Post, new { @class = "form-horizontal input-sm" }))
                {
                    <div class="form-group row">
                        <label class="col-md-2 col-form-label">Name</label>
                        <div class="col-md-9">
                            @Html.TextBoxFor(m => m.Name, new { @class = "form-control input-sm" })
                            @Html.ValidationMessageFor(m => m.Name, null, new { @class = "help-block text-danger" })
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-md-2 col-form-label">Phone</label>
                        <div class="col-md-9">
                            @Html.TextBoxFor(m => m.Phone, new { @class = "form-control input-sm" })
                            @Html.ValidationMessageFor(m => m.Phone, null, new { @class = "help-block text-danger" })
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-md-2 col-form-label">Address</label>
                        <div class="col-md-9">
                            @Html.TextBoxFor(m => m.Address, new { @class = "form-control input-sm" })
                            @Html.ValidationMessageFor(m => m.Address, null, new { @class = "help-block text-danger" })
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-md-12">
                            <button class="btn btn-sm btn-primary" type="submit" id="btnSubmit">
                                <i class="fa fa-dot-circle-o"></i> Save
                            </button>
                            &nbsp;
                            <a class="btn btn-sm btn-danger" href="~/Hospital/List">
                                <i class="fa fa-ban"></i> Cancel
                            </a>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-12">

                            @if (ViewBag.ErrorMessage != null && !string.IsNullOrEmpty(ViewBag.ErrorMessage))
                            {
                                <div class="text-danger">
                                    @ViewBag.ErrorMessage
                                </div>
                            }
                            @if (ViewBag.ErrorMessageList != null)
                            {
                                <div class="text-danger">
                                    @foreach (var item in ViewBag.ErrorMessageList)
                                    {
                                        <span>@item</span>
                                        <br />
                                    }
                                </div>
                            }

                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
    <!-- /.col-->
</div>

HealthyLifeStyle.Web/Views/Hospital/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Hastane Güncelleme";
}

@model HealthyLifeStyle.Web.Models.Hospital.AddViewModel



<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <strong>Hospital Add</strong>
            </div>
            <div class="card-body">

                @using (Html.BeginForm("Edit", "Hospital", FormMethod.Post, new { @class = "form-horizontal input-sm" }))
                {
                    @Html.HiddenFor(m => m.Id)
                    <div class="form-group row">
                        <label class="col-md-2 col-form-label">Name</label>
                        <div class="col-md-9">
                            @Html.TextBoxFor(m => m.Name, new { @class = "form-control input-sm" })
                            @Html.ValidationMessageFor(m => m.Name, null, new { @class = "help-block text-danger" })
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-md-2 col-form-label">Phone</label>
                        <div class="col-md-9">
                            @Html.TextBoxFor(m => m.Phone, new { @class = "form-control input-sm" })
                            @Html.ValidationMessageFor(m => m.Phone, null, new { @class = "help-block text-danger" })
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-md-2 col-form-label">Address</label>
                        <div class="col-md-9">
                            @Html.TextBoxFor(m => m.Address, new { @class = "form-control input-sm" })
                            @Html.ValidationMessageFor(m => m.Address, null, new { @class = "help-block text-danger" })
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-md-12">
                            <button class="btn btn-sm btn-primary" type="submit" id="btnSubmit">
                                <i class="fa fa-dot-circle-o"></i> Save
                            </button>
                            &nbsp;
                            <a class="btn btn-sm btn-danger" href="~/Hospital/List">
                                <i class="fa fa-ban"></i> Cancel
                            </a>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-12">

                            @if (ViewBag.ErrorMessage != null && !string.IsNullOrEmpty(ViewBag.ErrorMessage))
                            {
                                <div class="text-danger">
                                    @ViewBag.ErrorMessage
                                </div>
                            }
                            @if (ViewBag.ErrorMessageList != null)
                            {
                                <div class="text-danger">
                                    @foreach (var item in ViewBag.ErrorMessageList)
                                    {
                                        <span>@item</span>
                                        <br />
                                    }
                                </div>
                            }

                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
    <!-- /.col-->
</div>

HealthyLifeStyle.Web/Views/Hospital/List.cshtml
@model List<HealthyLifeStyle.Web.Models.Hospital.ListViewModel>

@{
    ViewData["Title"] = "Hastane Listesi";
}

<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <i class="fa fa-align-justify"></i> Hospital List

            </div>
            <div class="card-body">

                <div class="row">
                    <div class="col-lg-12">
                    </div>
                </div>

                <div class="table-responsive">
                    <table class="table table-responsive-sm table-bordered table-striped table-sm">
                        <thead>
                            <tr>

                                <th>*</th>
                                <th>
                                    Name

                                </th>
                                <th>
                                    Phone
                                </th>
                            </tr>
                        </thead>
                        <tbody>

                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td><a class="btn btn-sm btn-danger" href="~/Hospital/Edit/@item.Id">Edit</a></td>
                                    <td>@item.Name</td>
                                    <td>@item.Phone</td>
                                </tr>
                            }

                        </tbody>
                    </table>

                </div>

                <nav>
                </nav>

                @if (ViewBag.ErrorMessage != null && !string.IsNullOrEmpty(ViewBag.ErrorMessage))
                {
                    <div class="text-danger">
                        @ViewBag.ErrorMessage
                    </div>
                }
                @if (ViewBag.ErrorMessageList != null)
                {
                    <div class="text-danger">
                        @foreach (var item in ViewBag.ErrorMessageList)
                        {
                            <span>@item</span>
                            <br />
                        }
                    </div>
                }

            </div>
        </div>
    </div>
    <!-- /.col-->
</div>

@section Scripts {
    <!-- pagesize ve current page js  -->
    <script>
       
    </script>

}

HealthyLifeStyle.Web/Views/Hospital/_ErrorNotExist.cshtml
@{
    ViewBag.Title = "Error Not Exist";
}

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">

        <div class="card">
            <div class="card-header">
                <strong>@ViewBag.Title</strong>
            </div>
            <div class="card-body">
                Kayıt Bulunamadı.
            </div>
        </div>

    </div>
</div>