HealthyLifeStyle.Web/Models/Home/ListViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace HealthyLifeStyle.Web.Models.Home
{
    public class ListViewModel
    {
       
        public string Name { get; set; }
        
        public string Phone { get; set; }

        public string Address { get; set; }
    }
}

HealthyLifeStyle.Web/Models/Hospital/AddViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace HealthyLifeStyle.Web.Models.Hospital
{
    public class AddViewModel
    {
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        
    }
}

HealthyLifeStyle.Web/Models/Hospital/ListViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace HealthyLifeStyle.Web.Models.Hospital
{
    public class ListViewModel
    {

        public int Id { get; set; }
       
        public string Name { get; set; }
        
        public string Phone { get; set; }
       
        public string Address { get; set; }
    }
}

HealthyLifeStyle.Web/Models/NeedForBlood/AddViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;

namespace HealthyLifeStyle.Web.Models.NeedForBlood
{
    public class AddViewModel
    {
        public int Id { get; set; }

        [Required]
        public int BloodGroupId { get; set; }

        [Required]
        public int Count { get; set; }

        //select list
        public List<SelectListItem>? BloodGroupSelectList { get; set; }
    }
}

HealthyLifeStyle.Web/Models/NeedForBlood/ListViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace HealthyLifeStyle.Web.Models.NeedForBlood
{
    public class ListViewModel
    {
        public int Id { get; set; }
      
        public string BloodGroup_Name { get; set; }
       
        public int HospitalId { get; set; }
       
        public int Count { get; set; }
    }
}

HealthyLifeStyle.Web/Models/User/AddViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;

namespace HealthyLifeStyle.Web.Models.User
{
    public class AddViewModel
    {
   
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        public string LastName { get; set; }

        [Required]
        public int BloodGroupId { get; set; }
   
        public string GSM { get; set; }

        [Required]
        public string UserName { get; set; }

        [Required]
        public string Password { get; set; }

        public int? HospitalId { get; set; }

        //select list
        public List<SelectListItem>? BloodGroupSelectList { get; set; }
        public List<SelectListItem>? HospitalSelectList { get; set; }
    }
}

HealthyLifeStyle.Web/Models/User/ListViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace HealthyLifeStyle.Web.Models.User
{
    public class ListViewModel
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public string LastName { get; set; }
        
        public string GSM { get; set; }

        public string UserName { get; set; }

        public int UserType { get; set; }


        public string BloodGroup_Name { get; set; }
        public string Hospital_Name { get; set; }
    }
}

HealthyLifeStyle.Web/Controllers/NeedForBloodController.cs
using HealthyLifeStyle.Business.Interfaces;
using HealthyLifeStyle.Business.Services;
using HealthyLifeStyle.Types.Entity;
using HealthyLifeStyle.Web.Models.Common;
using HealthyLifeStyle.Web.Models.NeedForBlood;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace HealthyLifeStyle.Web.Controllers
{
    public class NeedForBloodController : Controller
    {
        private readonly INeedForBloodService _needForBloodService;
        private readonly IBloodGroupService _bloodGroupService;

        public NeedForBloodController(INeedForBloodService needForBloodService, IBloodGroupService bloodGroupService)
        {
            _needForBloodService = needForBloodService;
            _bloodGroupService = bloodGroupService;
        }
        public IActionResult List()
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("HealthyLifeStyle_User_Id")))
            {
                return RedirectToAction("Login", "User");
            }
            if (HttpContext.Session.GetInt32("HealthyLifeStyle_User_UserType") != (int)UserType.Hospital)
            {
                return RedirectToAction("NotAuthorized", "User");
            }

            var hospitalId = HttpContext.Session.GetString("HealthyLifeStyle_User_HospitalId");
            if (string.IsNullOrEmpty(hospitalId))
            {
                return RedirectToAction("NotAuthorized", "User");
            }

            List<ListViewModel> model = new List<ListViewModel>();

            var needForBloodList = _needForBloodService.GetAllWithDetailByHospitalId(Convert.ToInt32(hospitalId));
            if (needForBloodList != null)
            {
                foreach (var item in needForBloodList)
                {
                    ListViewModel needForBlood = new ListViewModel()
                    {
                        Id = item.Id,
                        BloodGroup_Name = item.BloodGroup_Name,
                        Count = item.Count,
                        HospitalId = item.HospitalId
                    };
                    model.Add(needForBlood);
                }
            }
            return View(model);
        }

        public IActionResult Add()
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("HealthyLifeStyle_User_Id")))
            {
                return RedirectToAction("Login", "User");
            }
            if (HttpContext.Session.GetInt32("HealthyLifeStyle_User_UserType") != (int)UserType.Hospital)
            {
                return RedirectToAction("NotAuthorized", "User");
            }
            var hospitalId = HttpContext.Session.GetString("HealthyLifeStyle_User_HospitalId");
            if (string.IsNullOrEmpty(hospitalId))
            {
                return RedirectToAction("NotAuthorized", "User");
            }

            AddViewModel model = new AddViewModel();
            model.BloodGroupSelectList = GetBloodGroupSelectList();

            return View(model);
        }

        [HttpPost]
        public IActionResult Add(AddViewModel model)
        {
            if (!ModelState.IsValid)
            {
                model.BloodGroupSelectList = GetBloodGroupSelectList();
                return View(model);
            }
            model.BloodGroupSelectList = GetBloodGroupSelectList();
            var hospitalId = HttpContext.Session.GetString("HealthyLifeStyle_User_HospitalId");
            if (string.IsNullOrEmpty(hospitalId))
            {
                return RedirectToAction("NotAuthorized", "User");
            }

            var isExist = _needForBloodService.GetByHospitalIdAndBloodGroupId(Convert.ToInt32(hospitalId), model.BloodGroupId);
            if (isExist !=null)
            {
                ViewBag.ErrorMessage = "Kayıt zaten mevcut.Lütfen mevcut kaydın sayısını güncelleyiniz.";
                model.BloodGroupSelectList = GetBloodGroupSelectList();
                return View(model);
            }

            NeedForBlood needForBlood = new NeedForBlood()
            {
                HospitalId = Convert.ToInt32(hospitalId),
                BloodGroupId = model.BloodGroupId,
                Count = model.Count
            };

            try
            {
                _needForBloodService.Add(needForBlood);
                return RedirectToAction(nameof(NeedForBloodController.List));
            }
            catch
            {
                ViewBag.ErrorMessage = "Not Saved.";
                return View(model);
            }
        }


        public IActionResult Edit(int id)
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("HealthyLifeStyle_User_Id")))
            {
                return RedirectToAction("Login", "User");
            }
            if (HttpContext.Session.GetInt32("HealthyLifeStyle_User_UserType") != (int)UserType.Hospital)
            {
                return RedirectToAction("NotAuthorized", "User");
            }
            var hospitalId = HttpContext.Session.GetString("HealthyLifeStyle_User_HospitalId");
            if (string.IsNullOrEmpty(hospitalId))
            {
                return RedirectToAction("NotAuthorized", "User");
            }

            AddViewModel model = new AddViewModel();
            model.BloodGroupSelectList = GetBloodGroupSelectList();

            try
            {
                var result = _needForBloodService.GetById(id);
                if (result == null)
                {
                    return View("_ErrorNotExist");
                }
                model.Id = result.Id;
                model.BloodGroupId = result.BloodGroupId;
                model.Count = result.Count;
                return View(model);
            }
            catch (Exception)
            {
                ViewBag.ErrorMessage = "Record Not Found";
                return View("_ErrorNotExist");
            }
        }

        [HttpPost]
        public IActionResult Edit(AddViewModel model)
        {
            if (!ModelState.IsValid)
            {
                model.BloodGroupSelectList = GetBloodGroupSelectList();
                return View(model);
            }
            model.BloodGroupSelectList = GetBloodGroupSelectList();
            var hospitalId = HttpContext.Session.GetString("HealthyLifeStyle_User_HospitalId");
            if (string.IsNullOrEmpty(hospitalId))
            {
                return RedirectToAction("NotAuthorized", "User");
            }

            var needForBlood = _needForBloodService.GetById(model.Id);
            if (needForBlood == null)
            {
                return View("_ErrorNotExist");
            }

            needForBlood.Count = model.Count;
            
            try
            {
                _needForBloodService.Update(needForBlood);
                return RedirectToAction(nameof(NeedForBloodController.List));
            }
            catch
            {
                ViewBag.ErrorMessage = "Not Saved.";
                return View(model);
            }
        }


        [NonAction]
        private List<SelectListItem> GetBloodGroupSelectList()
        {
            // blood group select list 
            List<SelectListItem> resultList = new List<SelectListItem>();
            try
            {
                resultList = _bloodGroupService.GetAll().OrderBy(r => r.Name).Select(r => new SelectListItem() { Value = r.Id.ToString(), Text = r.Name }).ToList();
            }
            catch
            {
                resultList = new List<SelectListItem>();
            }
            return resultList;
        }
    }
}

HealthyLifeStyle.Web/Views/NeedForBlood/Add.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Kan İhtiyacı Ekle";
}

@model HealthyLifeStyle.Web.Models.NeedForBlood.AddViewModel


<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <strong>Kan İhtiyacı Ekle</strong>
            </div>
            <div class="card-body">

                @using (Html.BeginForm("Add", "NeedForBlood", FormMethod.Post, new { @class = "form-horizontal input-sm" }))
                {

                    <div class="form-group row">
                        <label class="col-md-2 col-form-label">Blood Group</label>
                        <div class="col-md-9">
                            @Html.DropDownListFor(m => m.BloodGroupId, Model.BloodGroupSelectList, "Select", new { @class = "form-control form-control-sm" })
                            @Html.ValidationMessageFor(m => m.BloodGroupId, null, new { @class = "help-block text-danger" })
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-md-2 col-form-label">Count</label>
                        <div class="col-md-9">
                            @Html.TextBoxFor(m => m.Count, new { @class = "form-control input-sm",@type = "number" })
                            @Html.ValidationMessageFor(m => m.Count, null, new { @class = "help-block text-danger" })
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-12">
                            <button class="btn btn-sm btn-primary" type="submit" id="btnSubmit">
                                <i class="fa fa-dot-circle-o"></i> Save
                            </button>
                            &nbsp;
                            <a class="btn btn-sm btn-danger" href="~/NeedForBlood/List">
                                <i class="fa fa-ban"></i> Cancel
                            </a>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-12">

                            @if (ViewBag.ErrorMessage != null && !string.IsNullOrEmpty(ViewBag.ErrorMessage))
                            {
                                <div class="text-danger">
                                    @ViewBag.ErrorMessage
                                </div>
                            }
                            @if (ViewBag.ErrorMessageList != null)
                            {
                                <div class="text-danger">
                                    @foreach (var item in ViewBag.ErrorMessageList)
                                    {
                                        <span>@item</span>
                                        <br />
                                    }
                                </div>
                            }

                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
    <!-- /.col-->
</div>

HealthyLifeStyle.Web/Views/NeedForBlood/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Kan İhtiyacı Güncelle";
}

@model HealthyLifeStyle.Web.Models.NeedForBlood.AddViewModel


<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <strong>Kan İhtiyacı Güncelle</strong>
            </div>
            <div class="card-body">

                @using (Html.BeginForm("Edit", "NeedForBlood", FormMethod.Post, new { @class = "form-horizontal input-sm" }))
                {
                    @Html.HiddenFor(m => m.Id)
                    <div class="form-group row">
                        <label class="col-md-2 col-form-label">Code</label>
                        <div class="col-md-9">
                            @Html.DropDownListFor(m => m.BloodGroupId, Model.BloodGroupSelectList, "Select", new { @class = "form-control form-control-sm", @readonly = "readonly"  })
                            @Html.ValidationMessageFor(m => m.BloodGroupId, null, new { @class = "help-block text-danger" })
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-md-2 col-form-label">Count</label>
                        <div class="col-md-9">
                            @Html.TextBoxFor(m => m.Count, new { @class = "form-control input-sm",@type = "number" })
                            @Html.ValidationMessageFor(m => m.Count, null, new { @class = "help-block text-danger" })
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-12">
                            <button class="btn btn-sm btn-primary" type="submit" id="btnSubmit">
                                <i class="fa fa-dot-circle-o"></i> Save
                            </button>
                            &nbsp;
                            <a class="btn btn-sm btn-danger" href="~/NeedForBlood/List">
                                <i class="fa fa-ban"></i> Cancel
                            </a>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-12">

                            @if (ViewBag.ErrorMessage != null && !string.IsNullOrEmpty(ViewBag.ErrorMessage))
                            {
                                <div class="text-danger">
                                    @ViewBag.ErrorMessage
                                </div>
                            }
                            @if (ViewBag.ErrorMessageList != null)
                            {
                                <div class="text-danger">
                                    @foreach (var item in ViewBag.ErrorMessageList)
                                    {
                                        <span>@item</span>
                                        <br />
                                    }
                                </div>
                            }

                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
    <!-- /.col-->
</div>

HealthyLifeStyle.Web/Views/NeedForBlood/List.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Hastane Kan İhtiyacı";
}

@model List<HealthyLifeStyle.Web.Models.NeedForBlood.ListViewModel>

<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <i class="fa fa-align-justify"></i> Kan İhtiyaç Listesi
            </div>
            <div class="card-body">

                <div class="row">
                </div>

                <div class="table-responsive">
                    <table class="table table-responsive-sm table-bordered table-striped table-sm">
                        <thead>
                            <tr>
                                <th>*</th>
                                <th>
                                    Blood Group
                                </th>
                                <th>
                                    Count
                                </th>

                            </tr>
                        </thead>
                        <tbody>

                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        <a class="btn btn-sm btn-danger" href="~/NeedForBlood/Edit/@item.Id">Edit</a>
                                    </td>
                                    <td>@item.BloodGroup_Name</td>
                                    <td>@item.Count</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>

                @if (ViewBag.ErrorMessage != null && !string.IsNullOrEmpty(ViewBag.ErrorMessage))
                {
                    <div class="text-danger">
                        @ViewBag.ErrorMessage
                    </div>
                }
                @if (ViewBag.ErrorMessageList != null)
                {
                    <div class="text-danger">
                        @foreach (var item in ViewBag.ErrorMessageList)
                        {
                            <span>@item</span>
                            <br />
                        }
                    </div>
                }

            </div>
        </div>
    </div>
    <!-- /.col-->
</div>

@section Scripts {
    <script>
        
    </script>
}